apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  database-name: dGVzdGRi  # Encodage en base64 de 'testdb'
  database-user: cG9zdGdyZXM=  # Encodage en base64 de 'postgres'
  database-password: cGdzM2NyM3Q=  # Encodage en base64 de 'pgs3cr3t'
